=== satishthota917471/ips-cx6/target/tomcat/webapps/contentservices/WEB-INF/classes/raml/schema/content-api-save-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "title": "Content Api schema",
  "description": "Payload schema to create or update documents.",
  "items": {
    "type": "object",
    "title": "Document",
    "description": "CMIS Document to create or update",
    "properties": {
      "id": {
        "type": "string",
        "title": "Document ID",
        "description": "ID of the existing document to update."
      },
      "path": {
        "type": "string",
        "title": "Document path",
        "description": "Path of the document to create or update. Folders in the path will be created automaticaly if needed."
      },
      "repositoryId": {
        "type": "string",
        "title": "Repository ID",
        "description": "Repository ID to which updating or creating document belongs."
      },
      "type": {
        "type": "string",
        "title": "Type of the document",
        "description": "The cmis type of the document",
        "default": "bb:structuredcontent"
      },
      "content": {
        "type": "string",
        "title": "Content",
        "description": "Content of the document to create or update"
      },
      "mimeType": {
        "type": "string",
        "description": "Content mime type",
        "default": "application/json; charset=utf-8"
      },
      "length": {
        "type": "integer",
        "title": "Length",
        "description": "Content length"
      },
      "properties": {
        "type": "object",
        "title": "Content item properties",
        "description": "Optional content item properties",
        "properties": {
          "cmis:createdBy": {
            "type": "string",
            "default": "admin"
          },
          "cmis:lastModifiedBy": {
            "type": "string",
            "default": "admin"
          }
        },
        "additionalProperties": true
      }
    },
    "required": ["repositoryId"],
    "anyOf": [
      {
        "required": ["id"]
      },
      {
        "required": ["path"]
      }
    ],
    "additionalProperties": false
  }
}

=== satishthota917471/ips-cx6/target/tomcat/webapps/contentservices/WEB-INF/classes/raml/example/content-api-save-request-example.json
[
  {
    "path": "/Generated content/my-portal/page-1/CXPContentWidgetd0e346eb-4cd4-4a8e-b545-9b9f2001cf7b/en-simpleContent",
    "repositoryId": "3fb006de-d333-4ab2-8a3e-6f5f3c2fb5d5",
    "type": "bb:structuredcontent",
    "content": "{\"article\":{\"contentbody\":\"\",\"bb:title\":\"\"},\"link\":{\"path\":\"\",\"linkRef\":\"\",\"browserRef\":\"\",\"target\":\"\"},\"image\":{\"path\":\"/gateway/api/contentservices/atom/3fb006de-d333-4ab2-8a3e-6f5f3c2fb5d5/content?id=10c0c785-e622-41df-a1d5-b9e452ea8886\",\"browserRef\":\"cs:@portalRepository:10c0c785-e622-41df-a1d5-b9e452ea8886\"},\"text\":{\"textcontent\":\"\"}}",
    "mimeType": "text/json",
    "properties": {
      "cmis:createdBy": "admin",
      "cmis:lastModifiedBy": "admin",
      "bb:locale": "en"
    }
  },
  {
    "path": "/folder-1/folder-2/myDocument",
    "repositoryId": "contentRepository",
    "type": "cmis:document",
    "content": "It was a bright and sunny day. The sun shone brilliantly in the clear, blue sky.",
    "mimeType": "text/plain",
    "properties": {
      "cmis:createdBy": "admin",
      "cmis:lastModifiedBy": "admin",
      "bb:locale": "en"
    }
  },
  {
    "id": "d0e346eb-4cd4-4a8e-b545-9b9f2001cf7b",
    "repositoryId": "3fb006de-d333-4ab2-8a3e-6f5f3c2fb5d5",
    "type": "cmis:document",
    "content": "Text to update."
  }
]
